config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :quotes

  # Defines the root path route ("/")
  root "quotes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quote.rb
# == Schema Information
#
# Table name: quotes
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Quote < ApplicationRecord
  default_scope { order(created_at: :desc) }
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[show edit update destroy]

  def index
    @quotes = Quote.all
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)

    if @quote.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to quotes_path, notice: "Quote was successfully created." }
      end
    else
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace('new_quote', partial: 'quotes/form', locals: { quote: @quote }) }
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    if @quote.update(quote_params)
      redirect_to quotes_path, notice: "Quote was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @quote.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to quotes_path, notice: "Quote was successfully destroyed." }
    end
  end

  private

  def set_quote
    @quote = Quote.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.slim
=form_with(model: quote, local: true, id: 'new_quote_form') do |form|
  -if quote.errors.any?
    .alert.alert-danger
      = quote.errors.full_messages.to_sentence.capitalize
  = form.text_field :name, class: "form-control", placeholder: "Name", autofocus: true
  = form.submit "Create quote", class: "btn btn-primary"

app/views/quotes/_quote.slim
= turbo_frame_tag dom_id(quote) do
  div id="#{dom_id(quote)}"
    div 
      = link_to quote.name, quote_path(quote), data: { turbo_frame: "_top" }
    div
      .d-flex.align-items-center.justify-content-end.gap-2
        = link_to edit_quote_path(quote), class: 'btn btn-secondary' do
          i.bi.bi-pencil
          span.d-none Edit
        = button_to quote, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
          i.bi.bi-trash
          span.d-none Delete

app/views/quotes/create.turbo_stream.slim
= turbo_stream.prepend "quotes" do 
  = render partial: "quote", locals: { quote: @quote }

= turbo_stream.append "quotes" do 
  javascript:
    document.getElementById('new_quote_form').delete()

app/views/quotes/destroy.turbo_stream.slim
= turbo_stream.remove "quote_#{@quote.id}"

app/views/quotes/edit.slim
main.container 
  = link_to sanitize("&larr; Back to quotes"), quotes_path, class: 'btn btn-secondary'

  .header 
    h1 Edit Quote
  =form_for(@quote, url: quote_path(@quote), method: :patch) do |form|
    = render "form", quote: @quote, form: form
    = form.submit 'Update Quote', class: 'btn btn-primary'

app/views/quotes/index.slim
main.container 
  .header.mb-4
    h1 Quotes
    = link_to 'New Quote', new_quote_path, class: 'btn btn-primary', data: { turbo_frame: "new_quote" }
  = turbo_frame_tag "new_quote"
  div id="quotes"
    =render @quotes

app/views/quotes/new.slim
= turbo_frame_tag "new_quote" do
  = render "form", quote: @quote

app/views/quotes/show.slim
main.container
  = link_to sanitize("&larr; Back to quotes"), quotes_path, class: 'btn btn-secondary'
  .header 
    h1 = @quote.name